services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: development
    container_name: cafe-zen-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      backend:
        condition: service_started
    networks:
      - cafe-zen-network
    command: npm run dev

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: development
    container_name: cafe-zen-backend
    ports:
      - "8787:8787"
    volumes:
      - ./backend:/app
      - backend_node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - cafe-zen-network
    command: npm run dev

  # データベースはまだ選定中のため、コメントアウト
  # database:
  #   image: postgres:15-alpine
  #   container_name: cafe-zen-db
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - pgdata:/var/lib/postgresql/data
  #   environment:
  #     - POSTGRES_USER=cafezenuser
  #     - POSTGRES_PASSWORD=cafezenpassword
  #     - POSTGRES_DB=cafezen
  #   networks:
  #     - cafe-zen-network

networks:
  cafe-zen-network:
    driver: bridge

volumes:
  frontend_node_modules:
  backend_node_modules:
  # pgdata: # データベースコンテナのデータ永続化用（DBを使用する場合コメント解除）